In [1]:
import numpy as np

y = np.array([1, 2, 3, 4, 5, 6])
y_hat = np.array([5, 4, 2, 6, 7, 5])

mse = (1 / y.size) * sum((y - y_hat)**2)
mae = (1 / y.size) * sum(abs(y - y_hat))
print("MSE:", mse)
print("MAE:", mae)

MSE: 5.0
MAE: 2.0


In [23]:
import numpy as np
import os

data_path = 'metricas'
metrics = list()
for filename in os.listdir(data_path):
    f = os.path.join(data_path, filename)
    # checking if it is a file
    if os.path.isfile(f):
        metric = np.loadtxt(data_path + '/' + filename)
        metrics.append(metric)


np.array(metrics)
corr_matrix = np.corrcoef(metrics)

np.savetxt("correlation_matrix.csv", corr_matrix, delimiter=",", fmt='%.3f')
print(corr_matrix)

[[1.         0.69010372 0.45352531 ... 0.69785    0.57752844 0.26098201]
 [0.69010372 1.         0.51681446 ... 0.8949475  0.74587594 0.53090209]
 [0.45352531 0.51681446 1.         ... 0.65153797 0.47423001 0.25330423]
 ...
 [0.69785    0.8949475  0.65153797 ... 1.         0.73799085 0.4984417 ]
 [0.57752844 0.74587594 0.47423001 ... 0.73799085 1.         0.35553814]
 [0.26098201 0.53090209 0.25330423 ... 0.4984417  0.35553814 1.        ]]
